'use client';
import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { Minus, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Completion, Lang, State } from '@/lib/domain';

const translator=(lang:Lang)=>(es:string,ca:string,en:string)=>lang==='ca'?ca:lang==='en'?en:es;

export function CorrectionForm({completion,onSubmit,busy,lang}:{completion:Completion;onSubmit:(amount:number,reason:string)=>void;busy:boolean;lang:Lang}){
  const [all,setAll]=useState(true),[amount,setAmount]=useState(1),t=translator(lang),value=all?completion.xp:amount;
  const change=(next:number)=>setAmount(Math.max(1,Math.min(completion.xp,next)));
  return <form onSubmit={e=>{e.preventDefault();onSubmit(value,String(new FormData(e.currentTarget).get('reason')));}}>
    <fieldset className="correction-options"><legend>{t('Cuántos Xp retiramos','Quants Xp retirem','How much Xp to remove')}</legend><small>{t('Corrige solo lo anotado de más. No es una multa.','Corregeix només el que es va anotar de més. No és una multa.','Correct only what was recorded too much. This is not a penalty.')}</small><label><input type="radio" name="scope" checked={all} onChange={()=>setAll(true)}/>{t('Todos los Xp','Tots els Xp','All Xp')} ({completion.xp})</label><label><input type="radio" name="scope" checked={!all} onChange={()=>setAll(false)}/>{t('Solo una parte','Només una part','Only some')}</label></fieldset>
    {!all&&<div className="amount-selector"><button type="button" className="amount-step" aria-label={t('Restar un Xp','Restar un Xp','Subtract one Xp')} onClick={()=>change(amount-1)} disabled={amount<=1}><Minus size={16}/></button><input aria-label={t('Xp a retirar','Xp a retirar','Xp to remove')} type="range" min={1} max={completion.xp} step={1} value={amount} onChange={e=>change(+e.target.value)}/><input aria-label={t('Cantidad exacta de Xp','Quantitat exacta de Xp','Exact Xp amount')} type="number" required min={1} max={completion.xp} step={1} value={amount} onChange={e=>change(+e.target.value)}/><button type="button" className="amount-step" aria-label={t('Sumar un Xp','Sumar un Xp','Add one Xp')} onClick={()=>change(amount+1)} disabled={amount>=completion.xp}><Plus size={16}/></button></div>}
    <output className="correction-preview">{completion.xp} − {value} = <strong>{completion.xp-value} Xp</strong><small>{completion.xp-value>0?t('La misión sigue hecha.','La missió continua feta.','The mission stays complete.'):t('La misión volverá a estar pendiente.','La missió tornarà a estar pendent.','The mission becomes pending again.')}</small></output>
    <label>{t('Qué estamos corrigiendo','Què corregim','What are we correcting')}<small>{t('Una frase breve ayuda a que todo el mundo entienda el ajuste.','Una frase curta ajuda que tothom entengui l’ajust.','A short sentence helps everyone understand the adjustment.')}</small><textarea name="reason" required maxLength={300} rows={2} placeholder={t('Por ejemplo: Xp registrados de más','Per exemple: Xp registrats de més','For example: too much Xp recorded')}/></label>
    <Button type="submit" className="primary wide" disabled={busy}>{t('Guardar ajuste','Desar ajust','Save adjustment')}</Button>
  </form>;
}

export function CycleSettings({state,lang,busy,onSave}:{state:State;lang:Lang;busy:boolean;onSave:(day:number,time:string)=>void}){
  const [day,setDay]=useState(state.cycleRule?.day??5),[time,setTime]=useState(state.cycleRule?.time??'18:00'),t=translator(lang),locale=lang==='ca'?'ca-ES':lang==='en'?'en-GB':'es-ES';
  return <form onSubmit={e=>{e.preventDefault();onSave(day,time);}}><div className="form-grid"><label>{t('Día del cierre','Dia del tancament','Closing day')}<small>{t('Será el último día de la semana en todas las vistas.','Serà l’últim dia de la setmana a totes les vistes.','It becomes the final day of every week view.')}</small><select value={day} onChange={e=>setDay(+e.target.value)}>{[1,2,3,4,5,6,0].map(d=><option value={d} key={d}>{new Date(`2026-09-${20+d}T12:00:00Z`).toLocaleDateString(locale,{weekday:'long'})}</option>)}</select></label><label>{t('Hora del cierre','Hora del tancament','Closing time')}<small>{t('El balance queda listo a esta hora.','El balanç queda llest a aquesta hora.','The balance is ready at this time.')}</small><input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label></div><p className="muted">Europe/Madrid · {t('El cambio ajusta el ciclo en curso; los cierres anteriores conservan sus fechas.','El canvi ajusta el cicle en curs; els tancaments anteriors conserven les dates.','The change adjusts the open cycle; past closes keep their dates.')}</p><Button type="submit" variant="outline" disabled={busy||!time}>{t('Guardar cierre','Desar tancament','Save close')}</Button></form>;
}

export function ButtonHints({lang}:{lang:Lang}){
  const [hint,setHint]=useState<{text:string;x:number;y:number}|null>(null);
  useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const t=translator(lang);const show=(event:Event)=>{const button=(event.target as Element)?.closest?.('button,[role="button"],summary');if(!button)return;clearTimeout(timer);const label=button.getAttribute('data-help')||button.getAttribute('title')||button.getAttribute('aria-label')||button.textContent?.trim();if(!label)return;const text=button.getAttribute('data-help')||button.getAttribute('title')||(button.getAttribute('role')==='tab'?t('Abrir: ','Obrir: ','Open: '):'')+label;const rect=button.getBoundingClientRect();timer=setTimeout(()=>setHint({text,x:Math.min(window.innerWidth-150,Math.max(150,rect.left+rect.width/2)),y:rect.bottom+60>window.innerHeight?Math.max(8,rect.top-60):rect.bottom+8}),event.type==='focusin'?100:450);};const hide=()=>{clearTimeout(timer);setHint(null);};document.addEventListener('pointerover',show);document.addEventListener('focusin',show);document.addEventListener('pointerout',hide);document.addEventListener('focusout',hide);document.addEventListener('keydown',hide);document.addEventListener('pointerdown',hide);window.addEventListener('scroll',hide,true);return()=>{hide();document.removeEventListener('pointerover',show);document.removeEventListener('focusin',show);document.removeEventListener('pointerout',hide);document.removeEventListener('focusout',hide);document.removeEventListener('keydown',hide);document.removeEventListener('pointerdown',hide);window.removeEventListener('scroll',hide,true);};},[lang]);
  return hint?createPortal(<div className="button-hint" role="tooltip" style={{left:hint.x,top:hint.y}}>{hint.text}</div>,document.body):null;
}
