'use client';
import { useState } from 'react';
import { Award, CalendarDays, ChevronLeft, ChevronRight, Flame, History, RotateCcw, Sparkles, Trophy, Gift, BedDouble, Shirt, Backpack, ShowerHead, Utensils, ListChecks, Film, Headphones, Gamepad2, BookOpen } from 'lucide-react';
import { dateInMadrid, names, shiftDay, words, type Child, type Lang, type State, type Completion } from '@/lib/domain';
import { inCycle, madridTime, weekOrder, type Cycle } from '@/lib/cycles';

type Mode = 'day'|'week'|'month'|'year';
const date=(s:string)=>new Date(s+'T12:00:00Z');
const iso=(d:Date)=>d.toISOString().slice(0,10);
const icons={bed:BedDouble,shirt:Shirt,backpack:Backpack,shower:ShowerHead,utensils:Utensils,list:ListChecks,gift:Gift,film:Film,headphones:Headphones,game:Gamepad2,book:BookOpen,sparkles:Sparkles};
const net=(rows:Completion[])=>rows.reduce((n,c)=>n+(c.reversed?0:c.xp),0);
function range(a:string,b:string){const r:string[]=[];for(let d=a;d<=b;d=shiftDay(d,1))r.push(d);return r;}
function bounds(mode:Mode,anchor:string,cycle?:Cycle){
  if(mode==='week'&&cycle)return [dateInMadrid(new Date(cycle.start)),dateInMadrid(new Date(cycle.end))];
  if(mode==='year')return [anchor.slice(0,4)+'-01-01',anchor.slice(0,4)+'-12-31'];
  if(mode==='month')return [anchor.slice(0,7)+'-01',iso(new Date(Date.UTC(+anchor.slice(0,4),+anchor.slice(5,7),0,12)))];
  return [anchor,anchor];
}
function streak(s:State,child:Child,through:string){
  const active=new Set(s.completions.filter(c=>c.child===child&&!c.reversed&&c.day<=through).map(c=>c.day));
  const first=[...active].sort()[0];if(!first)return {current:0,best:0};
  const paused=(day:string)=>s.pauses.some(p=>p.child===child&&day>=p.from&&day<=p.to&&(!p.cancelledAt||day<dateInMadrid(new Date(p.cancelledAt))));
  let current=0,best=0;for(const day of range(first,through)){if(active.has(day)){current++;best=Math.max(best,current);}else if(!paused(day)&&day!==through)current=0;}
  return {current,best};
}

export function ProgressView({state,child,lang,parent,onReverse,onUndo,onUndoChange,busy}:{state:State;child:Child;lang:Lang;parent:boolean;onReverse:(id:string)=>void;onUndo:(id:string)=>void;onUndoChange:(id:string)=>void;busy:boolean}){
  const today=dateInMadrid(),[mode,setMode]=useState<Mode>('week'),[anchor,setAnchor]=useState(today),[cycleId,setCycleId]=useState<string|null>(null),[dayPart,setDayPart]=useState<'all'|'all-day'|'morning'|'afternoon'|'evening'>('all');
  const t=(es:string,ca:string,en:string)=>lang==='ca'?ca:lang==='en'?en:es;
  const locale=lang==='ca'?'ca-ES':lang==='en'?'en-GB':'es-ES';
  const cycles=state.cycles??[],cycle=cycles.find(c=>c.id===cycleId)??cycles.at(-1),cycleIndex=cycle?cycles.indexOf(cycle):-1;
  const [start,end]=bounds(mode,anchor,cycle),days=range(start,end),all=state.completions.filter(c=>c.child===child);
  const inRange=all.filter(c=>mode==='week'&&cycle?inCycle(c,cycle):c.day>=start&&c.day<=end);
  const spent=state.redemptions.filter(r=>r.child===child&&r.status!=='cancelled'&&(mode==='week'&&cycle?r.at>=cycle.start&&r.at<cycle.end:dateInMadrid(new Date(r.at))>=start&&dateInMadrid(new Date(r.at))<=end));
  const xp=net(inRange),gross=inRange.reduce((n,c)=>n+(c.originalXP??c.xp),0),cost=spent.reduce((n,r)=>n+r.xp,0),tasks=inRange.filter(c=>!c.reversed).length;
  const st=streak(state,child,end<today?end:today);
  const fmt=(d:string,options:Intl.DateTimeFormatOptions={day:'numeric',month:'short'})=>date(d).toLocaleDateString(locale,options);
  const label=mode==='year'?start.slice(0,4):mode==='month'?fmt(start,{month:'long',year:'numeric'}):mode==='day'?fmt(start,{weekday:'long',day:'numeric',month:'long',year:'numeric'}):`${fmt(start)} — ${fmt(end,{day:'numeric',month:'short',year:'numeric'})}`;
  function drill(next:Mode,day:string){setMode(next);setAnchor(day);setDayPart('all');}
  function navigate(n:number){if(mode==='week'){const c=cycles[cycleIndex+n];if(c)setCycleId(c.id);return;}const d=date(anchor);if(mode==='day')d.setUTCDate(d.getUTCDate()+n);if(mode==='month')d.setUTCMonth(d.getUTCMonth()+n,1);if(mode==='year')d.setUTCFullYear(d.getUTCFullYear()+n,0,1);setAnchor(iso(d));setDayPart('all');}
  const groups=mode==='year'?Array.from({length:12},(_,i)=>{const key=`${start.slice(0,4)}-${String(i+1).padStart(2,'0')}`;return {key,label:fmt(key+'-01',{month:'long'}),date:key+'-01',rows:inRange.filter(c=>c.day.startsWith(key)),next:'month' as Mode};}):mode==='day'?(['all-day','morning','afternoon','evening'] as const).map((part,i)=>({key:part,label:[t('Todo el día','Tot el dia','All day'),t('Mañana','Matí','Morning'),t('Tarde','Tarda','Afternoon'),t('Noche','Vespre','Night')][i],date:start,rows:inRange.filter(c=>(c.category??state.tasks.find(task=>task.id===c.taskId)?.category)===part),next:'day' as Mode})):days.map((day,i)=>({key:day,label:mode==='week'&&i===0&&cycle?`${t('Arranque','Inici','Start')} · ${madridTime(new Date(cycle.start))}`:mode==='week'?fmt(day,{weekday:'long'}):fmt(day,{day:'numeric',month:'short'}),date:day,rows:inRange.filter(c=>c.day===day),next:'day' as Mode}));
  const visibleLog=mode==='day'&&dayPart!=='all'?inRange.filter(c=>(c.category??state.tasks.find(task=>task.id===c.taskId)?.category)===dayPart):inRange;
  const max=Math.max(1,...groups.map(g=>g.rows.reduce((n,c)=>n+(c.originalXP??c.xp),0)));
  const previousAnchor=(()=>{const d=date(anchor);if(mode==='day')d.setUTCDate(d.getUTCDate()-1);if(mode==='month')d.setUTCMonth(d.getUTCMonth()-1,1);if(mode==='year')d.setUTCFullYear(d.getUTCFullYear()-1,0,1);return iso(d);})();
  const previousCycle=cycles[cycleIndex-1],[previousStart,previousEnd]=bounds(mode,previousAnchor,previousCycle);
  const previous=net(all.filter(c=>mode==='week'?(previousCycle?inCycle(c,previousCycle):false):c.day>=previousStart&&c.day<=previousEnd));
  const lastClosed=cycles.filter(c=>c.closed).at(-1);
  const latestChanges=(state.changes??[]).filter(c=>{const item=c.after??c.before;return item&&('child'in item?item.child===child:item.children.includes(child));}).slice().reverse().slice(0,12);
  const weekDays=mode==='week'&&cycle?Array.from({length:7},(_,i)=>(cycle.day+1+i)%7):weekOrder(state);
  return <div className="progress-history">
    <div className="period-toolbar"><div className="period-toggle" aria-label={t('Escala del historial','Escala de l’historial','History scale')}>{(['day','week','month','year'] as Mode[]).map((m,i)=><button key={m} className={mode===m?'active':''} aria-pressed={mode===m} onClick={()=>{setMode(m);setAnchor(today);setCycleId(null);}}>{[t('Día','Dia','Day'),t('Semana','Setmana','Week'),t('Mes','Mes','Month'),t('Año','Any','Year')][i]}</button>)}</div><div className="period-nav"><button aria-label={t('Periodo anterior','Període anterior','Previous period')} disabled={mode==='week'&&cycleIndex<=0} onClick={()=>navigate(-1)}><ChevronLeft/></button><strong>{label}</strong><button aria-label={t('Periodo siguiente','Període següent','Next period')} disabled={mode==='week'?cycleIndex>=cycles.length-1:end>=today} onClick={()=>navigate(1)}><ChevronRight/></button></div></div>
    <div className="period-context"><span className="tag">{names[child]} · {mode==='week'&&cycle?.closed?t('Ciclo cerrado','Cicle tancat','Closed cycle'):t('Historial real','Historial real','Real history')}</span><div className="button-row">{mode==='day'&&<button className="text-button" onClick={()=>{setMode('week');setCycleId(null);setDayPart('all');}}><ChevronLeft size={15}/>{t('Volver a la semana','Tornar a la setmana','Back to week')}</button>}<button className="text-button" onClick={()=>{setMode('week');setCycleId(null);setAnchor(today);setDayPart('all');}}>{t('Volver al ciclo actual','Tornar al cicle actual','Current cycle')}</button></div></div>
    {mode==='week'&&cycle&&<p className="inline-note">{t('Cierre','Tancament','Close')}: {fmt(end,{weekday:'long',day:'numeric',month:'long'})} · {cycle.time} · Europe/Madrid. {t('El arranque recoge lo hecho después del cierre anterior. Pulsa un día para ver su jornada completa.','L’inici inclou l’activitat posterior al tancament anterior. Toca un dia per veure’l complet.','Start includes activity after the previous close. Select a day to see the full calendar day.')}</p>}
    <div className="stats-grid history-stats"><section className="stat panel"><Trophy/><span>Xp {t('netos','nets','net')}</span><strong>{xp}<small> Xp</small></strong><small>{gross} {t('ganados','guanyats','earned')} − {gross-xp} {t('ajustados','ajustats','adjusted')}</small></section><section className="stat panel"><Gift/><span>{t('Xp en premios','Xp en premis','Reward Xp')}</span><strong>{cost}</strong><small>{spent.length} {t('canjes activos','bescanvis actius','active redemptions')}</small></section><section className="stat panel"><Flame/><span>{t('Misiones hechas','Missions fetes','Missions done')}</span><strong>{tasks}</strong><small>{st.current} {t('días de racha al final del periodo','dies de ratxa al final del període','day streak at period end')} · {t('récord','rècord','best')} {st.best}</small></section></div>
    <section className="panel period-chart"><div className="section-head"><div><h2><CalendarDays/>{t('El mapa de tus Xp','El mapa dels teus Xp','Your Xp map')}</h2><p>{t('Toca una barra. Hay historia dentro.','Toca una barra. Hi ha història a dins.','Select a bar. There is a story inside.')}</p></div><span className="comparison">{xp-previous>=0?'+':''}{xp-previous} Xp {t('frente al periodo anterior','respecte al període anterior','vs previous period')}{end>=today&&` · ${t('en curso','en curs','in progress')}`}</span></div><div className="chart-legend"><span className="legend-earned">Xp {t('conservados','conservats','retained')}</span><span className="legend-adjusted">{t('Xp retirados','Xp retirats','Xp removed')}</span></div>{mode==='day'&&<div className="daypart-filter" aria-label={t('Filtrar el registro del día','Filtrar el registre del dia','Filter day log')}>{(['all','all-day','morning','afternoon','evening'] as const).map(part=><button key={part} className={dayPart===part?'active':''} onClick={()=>setDayPart(part)}>{part==='all'?t('Todo el registro','Tot el registre','All activity'):part==='all-day'?t('Todo el día','Tot el dia','All day'):part==='morning'?t('Mañana','Matí','Morning'):part==='afternoon'?t('Tarde','Tarda','Afternoon'):t('Noche','Vespre','Night')}</button>)}</div>}<div className="chart-scroll"><div className={`explorer-bars ${mode}`} style={{gridTemplateColumns:`repeat(${groups.length},minmax(${mode==='week'?100:mode==='month'?48:75}px,1fr))`}}>{groups.map(g=>{const total=g.rows.reduce((n,c)=>n+(c.originalXP??c.xp),0),value=net(g.rows),isDay=mode==='day';return <button className={`explorer-bar ${isDay&&dayPart===g.key?'active':''} ${!isDay&&g.date===today?'today':''}`} key={g.key} disabled={!isDay&&g.date>today} onClick={()=>isDay?setDayPart(g.key as typeof dayPart):drill(g.next,g.date)} aria-label={`${g.label}, ${value} Xp. ${t('Ver detalle','Veure detall','View details')}`}><strong>{value} <small>Xp</small></strong><span className="bar-well"><i className="bar-net" style={{height:`${value/max*100}%`}}/><i className="bar-adjustment" style={{height:`${(total-value)/max*100}%`}}/></span><b>{g.label}</b>{mode==='week'&&<small>{fmt(g.date)}</small>}</button>})}</div></div></section>
    <div className="analytics-grid"><section className="panel"><h2><Sparkles/>{t('Dónde suman las misiones','On sumen les missions','Where missions add up')}</h2>{(['all-day','morning','afternoon','evening'] as const).map((category,i)=>{const rows=inRange.filter(c=>(c.category??state.tasks.find(t=>t.id===c.taskId)?.category)===category),value=net(rows);return <div className={`category-meter cat-${category}`} key={category}><div><strong>{[t('Todo el día','Tot el dia','All day'),t('Mañana','Matí','Morning'),t('Tarde','Tarda','Afternoon'),t('Noche','Vespre','Evening')][i]}</strong><span>{value} Xp · {rows.filter(c=>!c.reversed).length} {t('hechas','fetes','done')}</span></div><progress value={value} max={Math.max(1,xp)}/></div>})}<p className="muted">{t('Cada misión conserva sus Xp originales. Los ajustes quedan a la vista.','Cada missió conserva els Xp originals. Els ajustos són visibles.','Each mission keeps its original Xp. Adjustments stay visible.')}</p></section>
    <section className="panel"><h2><Flame/>{t('Constancia, sin presión','Constància, sense pressió','Consistency, no pressure')}</h2><p className="muted">{t('Los descansos programados protegen la racha. Un día tranquilo no resta Xp.','Els descansos programats protegeixen la ratxa. Un dia tranquil no resta Xp.','Scheduled breaks protect streaks. A quiet day never removes Xp.')}</p><div className="activity-map" aria-label={t('Calendario de actividad','Calendari d’activitat','Activity calendar')}>{weekDays.map(d=><span key={d} title={fmt(`2026-09-${20+d}`,{weekday:'long'})}>{fmt(`2026-09-${20+d}`,{weekday:'short'})}</span>)}{Array.from({length:(date(start).getUTCDay()-weekDays[0]+7)%7},(_,i)=><i key={`blank-${i}`}/>)}{days.map(d=>{const value=net(all.filter(c=>c.day===d&&!c.reversed)),paused=state.pauses.some(p=>p.child===child&&d>=p.from&&d<=p.to&&(!p.cancelledAt||d<dateInMadrid(new Date(p.cancelledAt))));return <button key={d} disabled={d>today} className={`${value?'has-xp':''} ${paused?'rest-day':''} ${d===today?'today':''}`} style={{opacity:value?Math.min(1,.48+value/65):1}} title={`${fmt(d,{day:'numeric',month:'long'})}: ${value} Xp${paused?' · '+t('Descanso','Descans','Rest'):''}`} aria-label={`${fmt(d,{day:'numeric',month:'long'})}, ${value} Xp`} onClick={()=>drill('day',d)}>{date(d).getUTCDate()}</button>})}</div></section></div>
    <section className="panel achievement-panel"><h2><Award/>{t('Logros con fecha','Assoliments amb data','Dated achievements')}</h2><div className="achievement-track">{[1,10,25,50,100].map((threshold,i)=>{const badge=state.badges?.find(b=>b.child===child&&b.threshold===threshold&&dateInMadrid(new Date(b.at))<=end);return <article key={threshold} className={badge?'unlocked':'locked'}><span>{['⚡','🧭','🏆','🚀','👑'][i]}</span><strong>{threshold} {t('misiones','missions','missions')}</strong><small>{badge?fmt(dateInMadrid(new Date(badge.at)),{day:'numeric',month:'short',year:'numeric'}):t('Por descubrir','Per descobrir','Still ahead')}</small></article>})}</div></section>
    <section className="panel"><h2><History/>{t('Registro del periodo','Registre del període','Period log')}<span className="count-badge">{visibleLog.length}</span></h2>{!visibleLog.length&&<div className="history-empty"><Sparkles/><p>{t('Sin misiones en este periodo. El historial no se inventa aventuras.','Sense missions en aquest període.','No missions in this period.')}</p></div>}{visibleLog.slice().sort((a,b)=>b.day.localeCompare(a.day)||b.at.localeCompare(a.at)).map(c=>{const Icon=icons[(c.icon??state.tasks.find(t=>t.id===c.taskId)?.icon??'sparkles') as keyof typeof icons]??Sparkles,last=c.adjustments?.at(-1);const canUndo=last&&!last.undoOf&&!last.undoneBy&&(parent||(c.actor===child&&c.day===today&&!c.adjustments?.some(a=>a.actor==='xavi'||a.actor==='mireia')));return <article className="history-record" key={c.id}><div className="record-row"><span className="record-icon"><Icon/></span><div><strong className={c.reversed?'struck':''}>{words(c.title,lang)}</strong><p>{fmt(c.day,{weekday:'long',day:'numeric',month:'short'})} · {names[c.actor]}</p></div><span className="xp-chip">{c.reversed?0:c.xp} Xp</span><div className="record-actions">{parent&&!c.reversed&&<button className="icon-action" disabled={busy} aria-label={t('Corregir Xp de esta misión','Corregir Xp d’aquesta missió','Adjust this mission Xp')} onClick={()=>onReverse(c.id)}><RotateCcw size={17}/></button>}{canUndo&&<button className="text-button" disabled={busy} onClick={()=>onUndo(c.id)}>{t('Deshacer ajuste','Desfer ajust','Undo adjustment')}</button>}</div></div>{c.adjustments?.length?<details><summary>{t('Ver ajustes','Veure ajustos','View adjustments')} · {c.adjustments.length}</summary>{c.adjustments.map(a=><p key={a.id}>{new Date(a.at).toLocaleString(locale,{timeZone:'Europe/Madrid'})} · {names[a.actor]} · {a.from} → {a.to} Xp · {a.reason}{a.undoneBy&&` · ${t('deshecho','desfet','undone')}`}</p>)}</details>:c.reason&&<p className="muted">{c.reason}</p>}</article>})}{spent.map(r=><div className="record-row" key={r.id}><span className="record-icon"><Gift/></span><div><strong>{words(r.title,lang)}</strong><p>{fmt(dateInMadrid(new Date(r.at)))} · {t('Canje','Bescanvi','Redemption')}</p></div><span className="xp-chip">−{r.xp} Xp</span></div>)}</section>
    {latestChanges.length>0&&<section className="panel"><details><summary>{t('Últimos cambios · deshacer','Últims canvis · desfer','Recent changes · undo')}</summary><p className="muted">{t('Disponible mientras no haya cambios posteriores que dependan de esta acción.','Disponible mentre no hi hagi canvis posteriors que en depenguin.','Available until later changes depend on the action.')}</p>{latestChanges.map(c=><div className="record-row" key={c.id}><div><strong>{c.title}</strong><p>{new Date(c.at).toLocaleString(locale)} · {names[c.actor]}</p></div>{!c.undoneBy?<button className="text-button" disabled={busy} onClick={()=>onUndoChange(c.id)}>{t('Deshacer','Desfer','Undo')}</button>:<small>{t('Deshecho','Desfet','Undone')}</small>}</div>)}</details></section>}
    <section className="panel cycle-finale"><span className="eyebrow">{t('CIERRE DE CICLO','TANCAMENT DE CICLE','CYCLE CLOSE')}</span><h2><Award/>{t('La semana, sin maquillaje','La setmana, sense maquillatge','The week, unfiltered')}</h2>{lastClosed?<><p>{fmt(dateInMadrid(new Date(lastClosed.start)))} — {fmt(dateInMadrid(new Date(lastClosed.end)))} · {lastClosed.time}</p><div className="closing-score"><strong>{lastClosed.snapshot?.[child]?.xp??0} <small>Xp</small></strong><span>{lastClosed.snapshot?.[child]?.tasks??0} {t('misiones al cierre','missions al tancament','missions at close')}</span></div><p className="muted">{t('Foto del cierre. Las correcciones posteriores siguen en el registro y en el saldo actual.','Foto del tancament. Els ajustos posteriors continuen al registre i al saldo actual.','Snapshot at close. Later adjustments remain in the log and current balance.')}{lastClosed.reconstructed&&` · ${t('Reconstruido del historial previo','Reconstruït de l’historial previ','Reconstructed from older history')}`}</p><button className="text-button" onClick={()=>{setMode('week');setCycleId(lastClosed.id);}}>{t('Explorar este ciclo','Explorar aquest cicle','Explore this cycle')}</button></>:<p>{t('El primer balance llegará al cerrar este ciclo. El saldo ya se puede usar.','El primer balanç arribarà en tancar aquest cicle. El saldo ja es pot fer servir.','The first summary arrives when this cycle closes. Your balance is already available.')}</p>}{cycle&&<small>{t('Próximo cierre','Proper tancament','Next close')}: {new Date(cycles.at(-1)!.end).toLocaleString(locale,{timeZone:'Europe/Madrid',weekday:'long',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small>}</section>
  </div>;
}
