'use client';

import Image from 'next/image';
import { BedDouble, CalendarDays, Check, Gift, Moon, Sparkles, Star, Trophy, Wallet } from 'lucide-react';
import { names, totals, words, type Child, type Lang, type State } from '@/lib/domain';

const dayNames = {
  es: ['L','M','X','J','V','S','D'], ca: ['Dl','Dt','Dc','Dj','Dv','Ds','Dg'], en: ['M','T','W','T','F','S','S'],
};
const weekDays = [1,2,3,4,5,6,0];

export function RulesView({state,child,lang,onRewards}:{state:State;child:Child;lang:Lang;onRewards:()=>void}) {
  const t=(es:string,ca:string,en:string)=>lang==='ca'?ca:lang==='en'?en:es;
  const tasks=state.tasks.filter(task=>task.status==='approved'&&task.children.includes(child));
  const reward=state.rewards.find(r=>r.id==='friend-sleepover'&&r.status==='approved'&&r.children.includes(child));
  const price=reward?.xp??1500;
  const balance=totals(state,child).balance;
  return <div className="rules-view">
    <section className="rules-hero"><div><span className="eyebrow">{t('REGLAS DEL JUEGO','REGLES DEL JOC','GAME RULES')}</span><h1>{t('Así se ganan los XP','Així es guanyen els XP','How XP works')}</h1><p>{t(`Las misiones de ${names[child]} suman XP. La constancia multiplica los puntos y acerca los premios.`,`Les missions de ${names[child]} sumen XP. La constància multiplica els punts i acosta els premis.`,`${names[child]}'s missions earn XP. Consistency multiplies points and brings rewards closer.`)}</p></div><Image src="/task-experience-emoji.png" alt="" width={180} height={180}/></section>
    <div className="rules-diagram" aria-label={t('Misiones, XP, bonus y premios','Missions, XP, bonus i premis','Missions, XP, bonuses and rewards')}>
      <div><Check/><strong>{t('Misiones','Missions','Missions')}</strong></div><b>→</b><div><Wallet/><strong>XP</strong></div><b>→</b><div><Sparkles/><strong>×2 / ×5</strong></div><b>→</b><div><Gift/><strong>{t('Premios','Premis','Rewards')}</strong></div>
    </div>
    <div className="rules-cards">
      <article className="rules-card"><CalendarDays/><h2>{t('La semana va de lunes a domingo','La setmana va de dilluns a diumenge','Monday to Sunday')}</h2><p>{t('Cada tarea cuenta los días y repeticiones que tiene asignados. Los objetivos semanales se registran una vez en cualquier día permitido.','Cada tasca compta els dies i repeticions assignats. Els objectius setmanals es registren una vegada en qualsevol dia permès.','Each task counts its assigned days and repetitions. Weekly goals are recorded once on any allowed day.')}</p><div className="rules-week">{dayNames[lang].map((d,i)=><span key={i}>{d}</span>)}</div></article>
      <article className="rules-card silver"><Star/><h2>{t('Una tarea completa: ×2','Una tasca completa: ×2','One complete task: ×2')}</h2><p>{t('Al terminar todos sus días y repeticiones de la semana, recibes tantos XP extra como dio esa tarea. Una tarea de 5 XP hecha cinco días suma 25 XP normales y 25 XP de bonus.','En completar tots els dies i repeticions de la setmana, reps tants XP extra com ha donat la tasca. Una tasca de 5 XP feta cinc dies suma 25 XP normals i 25 XP de bonus.','Finish every scheduled day and repetition to earn the same XP again. A 5 XP task done five days earns 25 normal XP and 25 bonus XP.')}</p></article>
      <article className="rules-card gold"><Trophy/><h2>{t('Todas las tareas: ×5','Totes les tasques: ×5','Every task: ×5')}</h2><p>{t('Al completar toda la semana, los XP de esas tareas valen cinco veces más. El ×5 sustituye a los ×2 ya recibidos: solo se añade la diferencia.','En completar tota la setmana, els XP d’aquestes tasques valen cinc vegades més. El ×5 substitueix els ×2 rebuts: només s’afegeix la diferència.','Finish the whole week and task XP is worth five times as much. The ×5 replaces earlier ×2 bonuses; only the difference is added.')}</p></article>
      <article className="rules-card"><Moon/><h2>{t('Descansos y correcciones','Descansos i correccions','Rest and corrections')}</h2><p>{t('Los padres pueden programar descansos: esos días dejan de exigirse para el bonus. Si corrigen una tarea, el bonus y el saldo se recalculan.','Els pares poden programar descansos: aquests dies deixen de ser necessaris per al bonus. Si corregeixen una tasca, el bonus i el saldo es recalculen.','Parents can schedule rest days. Those days stop being required for bonuses. Corrections recalculate bonuses and balances.')}</p></article>
    </div>
    <section className="rules-catalog"><h2>{t(`Misiones de ${names[child]}`,`Missions de ${names[child]}`,`${names[child]}'s missions`)}</h2><p>{t('Los días y los XP reflejan las reglas configuradas ahora por los padres.','Els dies i els XP reflecteixen les regles configurades ara pels pares.','Days and XP reflect the rules currently set by parents.')}</p><div className="rules-task-grid">{tasks.map(task=><article key={task.id}><strong>{words(task.title,lang)}</strong><small>{words(task.description,lang)}</small><b>+{task.xp} XP {task.cadence==='weekly'?t('por semana','per setmana','per week'):task.limit>1?`× ${task.limit} ${t('veces','vegades','times')}`:''}</b><div className="rules-schedule">{weekDays.map((d,i)=><span key={d} className={task.days.includes(d)?'on':''}>{dayNames[lang][i]}</span>)}</div></article>)}</div></section>
    <section className="rules-reward"><div><span className="eyebrow">{t('SUPER OBJETIVO','SUPER OBJECTIU','SUPER GOAL')}</span><h2><BedDouble/>{reward?words(reward.title,lang):t('Tus premios','Els teus premis','Your rewards')}</h2><p>{t(`Puedes ahorrar XP durante varias semanas o conseguir una semana perfecta. Al solicitarlo se reservan ${price} XP; los padres confirman la fecha. Si se cancela, vuelven al saldo.`,`Pots estalviar XP durant diverses setmanes o aconseguir una setmana perfecta. En demanar-ho es reserven ${price} XP; els pares confirmen la data. Si es cancel·la, tornen al saldo.`,`Save XP over several weeks or earn a perfect week. Requesting reserves ${price} XP; parents confirm the date. Cancellation returns them to your balance.`)}</p><strong>{Math.max(0,balance)} / {price} XP</strong><button onClick={onRewards}>{t('Ver premios','Veure premis','See rewards')}</button></div><div className="rules-cup"><Image src="/task-experience-emoji.png" alt="" width={220} height={220}/><span>{price} XP</span></div></section>
    <p className="rules-footnote">{t('Los XP gastados bajan el saldo, pero no borran la experiencia ni los niveles. Hay pequeñas sorpresas escondidas; las reglas no estropean la búsqueda.','Els XP gastats baixen el saldo, però no esborren l’experiència ni els nivells. Hi ha petites sorpreses amagades; les regles no espatllen la cerca.','Spent XP reduce the balance but never erase experience or levels. Small surprises are hidden; the rules leave the hunt intact.')}</p>
  </div>;
}
