'use client';

import Image from 'next/image';
import { BedDouble, CalendarDays, Check, Gift, Moon, Sparkles, Star, Trophy, Wallet } from 'lucide-react';
import { totals, words, type Child, type Lang, type State } from '@/lib/domain';
import { memberName } from '@/lib/family';

const dayNames = {
  es: ['L','M','X','J','V','S','D'], ca: ['Dl','Dt','Dc','Dj','Dv','Ds','Dg'], en: ['M','T','W','T','F','S','S'],
};
const weekDays = [1,2,3,4,5,6,0];

export function RulesView({state,child,lang,onRewards}:{state:State;child:Child;lang:Lang;onRewards:()=>void}) {
  const t=(es:string,ca:string,en:string)=>lang==='ca'?ca:lang==='en'?en:es;
  const tasks=state.tasks.filter(task=>task.status==='approved'&&task.children.includes(child));
  const reward=state.rewards.find(r=>r.id==='friend-sleepover'&&r.status==='approved'&&r.children.includes(child));
  const price=reward?.xp??1500;
  const balance=totals(state,child).balance;
  return <div className="rules-view">
    <section className="rules-hero"><div><span className="eyebrow">{t('REGLAS DEL JUEGO','REGLES DEL JOC','GAME RULES')}</span><h1>{t('Así se ganan los Xp','Així es guanyen els Xp','How Xp works')}</h1><p>{t(`Las misiones de ${memberName(state,child)} suman Xp. La constancia multiplica los puntos y acerca los premios.`,`Les missions de ${memberName(state,child)} sumen Xp. La constància multiplica els punts i acosta els premis.`,`${memberName(state,child)}'s missions earn Xp. Consistency multiplies points and brings rewards closer.`)}</p></div><Image src="/task-experience-emoji.png" alt="" width={180} height={180}/></section>
    <div className="rules-diagram" aria-label={t('Misiones, Xp, bonus y premios','Missions, Xp, bonus i premis','Missions, Xp, bonuses and rewards')}>
      <div><Check/><strong>{t('Misiones','Missions','Missions')}</strong></div><b>→</b><div><Wallet/><strong>Xp</strong></div><b>→</b><div><Sparkles/><strong>×2 / ×5</strong></div><b>→</b><div><Gift/><strong>{t('Premios','Premis','Rewards')}</strong></div>
    </div>
    <div className="rules-cards">
      <article className="rules-card"><CalendarDays/><h2>{t('Los bonus van de lunes a domingo','Els bonus van de dilluns a diumenge','Bonuses run Monday to Sunday')}</h2><p>{t('Cada misión cuenta los días y repeticiones que tiene asignados. Las misiones semanales se registran una vez en cualquier día permitido.','Cada missió compta els dies i repeticions assignats. Les missions setmanals es registren una vegada en qualsevol dia permès.','Each mission counts its assigned days and repetitions. Weekly missions are recorded once on any allowed day.')}</p><div className="rules-week">{dayNames[lang].map((d,i)=><span key={i}>{d}</span>)}</div></article>
      <article className="rules-card silver"><Star/><h2>{t('Una misión completa: ×2 total','Una missió completa: ×2 total','One complete mission: ×2 total')}</h2><p>{t('Completa todas las veces que toca esta misión durante la semana y duplicas sus Xp. Ejemplo: una misión de 5 Xp durante 5 días da 25 Xp base + 25 Xp de bonus = 50 Xp en total.','Completa totes les vegades que toca aquesta missió durant la setmana i dupliques els seus Xp. Exemple: una missió de 5 Xp durant 5 dies dona 25 Xp base + 25 Xp de bonus = 50 Xp en total.','Complete every scheduled occurrence of a mission this week to double that mission’s Xp. Example: 5 Xp on 5 days gives 25 base Xp + 25 bonus Xp = 50 Xp total.')}</p></article>
      <article className="rules-card gold"><Trophy/><h2>{t('Todas las misiones: ×5 total','Totes les missions: ×5 total','Every mission: ×5 total')}</h2><p>{t('Si completas todas las misiones programadas de la semana, sus Xp base terminan multiplicados ×5: 100 Xp base → 500 Xp total. El ×5 total sustituye a los bonus ×2; si ya recibiste alguno, solo se añade la diferencia. No se multiplican otra vez los bonus, ni cuentan objetivos puntuales ni descubrimientos.','Si completes totes les missions programades de la setmana, els seus Xp base acaben multiplicats ×5: 100 Xp base → 500 Xp en total. El ×5 total substitueix els bonus ×2; si ja n’has rebut algun, només s’afegeix la diferència. Els bonus no es tornen a multiplicar, i no compten els objectius puntuals ni els ous de Pasqua.','Complete every scheduled mission this week and its base Xp ends up multiplied by ×5: 100 base Xp → 500 Xp total. The ×5 total replaces ×2 bonuses already awarded; only the difference is added. Bonuses are not multiplied again, and one-off goals and discoveries do not count.')}</p></article>
      <article className="rules-card"><Moon/><h2>{t('Descansos y correcciones','Descansos i correccions','Rest and corrections')}</h2><p>{t('Los padres pueden programar descansos: esos días dejan de exigirse para el bonus. Si corrigen una misión, el bonus y el saldo se recalculan.','Els pares poden programar descansos: aquests dies deixen de ser necessaris per al bonus. Si corregeixen una missió, el bonus i el saldo es recalculen.','Parents can schedule rest days. Those days stop being required for bonuses. Corrections recalculate bonuses and balances.')}</p></article>
    </div>
    <section className="rules-catalog"><h2>{t(`Misiones de ${memberName(state,child)}`,`Missions de ${memberName(state,child)}`,`${memberName(state,child)}'s missions`)}</h2><p>{t('Los días y los Xp reflejan las reglas configuradas ahora por los padres.','Els dies i els Xp reflecteixen les regles configurades ara pels pares.','Days and Xp reflect the rules currently set by parents.')}</p><div className="rules-task-grid">{tasks.map(task=><article key={task.id}><strong>{words(task.title,lang)}</strong><small>{words(task.description,lang)}</small><b>+{task.xp} Xp {task.cadence==='weekly'?t('por semana','per setmana','per week'):task.limit>1?`× ${task.limit} ${t('veces','vegades','times')}`:''}</b><div className="rules-schedule">{weekDays.map((d,i)=><span key={d} className={task.days.includes(d)?'on':''}>{dayNames[lang][i]}</span>)}</div></article>)}</div></section>
    <section className="rules-reward"><div><span className="eyebrow">{t('PREMIO ESPECIAL','PREMI ESPECIAL','SPECIAL REWARD')}</span><h2><BedDouble/>{reward?words(reward.title,lang):t('Tus premios','Els teus premis','Your rewards')}</h2><p>{t(`Puedes ahorrar Xp durante varias semanas o conseguir una semana perfecta. Al solicitarlo se reservan ${price} Xp; los padres confirman la fecha. Si se cancela, vuelven al saldo.`,`Pots estalviar Xp durant diverses setmanes o aconseguir una setmana perfecta. En demanar-ho es reserven ${price} Xp; els pares confirmen la data. Si es cancel·la, tornen al saldo.`,`Save Xp over several weeks or earn a perfect week. Requesting reserves ${price} Xp; parents confirm the date. Cancellation returns them to your balance.`)}</p><strong>{Math.max(0,balance)} / {price} Xp</strong><button onClick={onRewards}>{t('Ver premios','Veure premis','See rewards')}</button></div><div className="rules-cup"><Image src="/task-experience-emoji.png" alt="" width={220} height={220}/><span>{price} Xp</span></div></section>
    <p className="rules-footnote">{t('Los Xp gastados bajan el saldo, pero no borran la experiencia ni los niveles. Hay pequeñas sorpresas escondidas; las reglas no estropean la búsqueda.','Els Xp gastats baixen el saldo, però no esborren l’experiència ni els nivells. Hi ha petites sorpreses amagades; les regles no espatllen la cerca.','Spent Xp reduce the balance but never erase experience or levels. Small surprises are hidden; the rules leave the hunt intact.')}</p>
  </div>;
}
