'use client';

import Image from 'next/image';
import { BedDouble, CalendarDays, Check, Gift, Moon, Sparkles, Star, Trophy, Wallet } from 'lucide-react';
import { names, totals, words, type Child, type Lang, type State } from '@/lib/domain';

const dayNames = {
  es: ['L','M','X','J','V','S','D'], ca: ['Dl','Dt','Dc','Dj','Dv','Ds','Dg'], en: ['M','T','W','T','F','S','S'],
};
const weekDays = [1,2,3,4,5,6,0];

export function RulesView({state,child,lang,onRewards}:{state:State;child:Child;lang:Lang;onRewards:()=>void}) {
  const t=(es:string,ca:string,en:string)=>lang==='ca'?ca:lang==='en'?en:es;
  const tasks=state.tasks.filter(task=>task.status==='approved'&&task.children.includes(child));
  const reward=state.rewards.find(r=>r.id==='friend-sleepover'&&r.status==='approved'&&r.children.includes(child));
  const price=reward?.xp??1500;
  const balance=totals(state,child).balance;
  return <div className="rules-view">
    <section className="rules-hero"><div><span className="eyebrow">{t('REGLAS DEL JUEGO','REGLES DEL JOC','GAME RULES')}</span><h1>{t('Así se ganan los Xp','Així es guanyen els Xp','How Xp works')}</h1><p>{t(`Las misiones de ${names[child]} suman Xp. La constancia multiplica los puntos y acerca los premios.`,`Les missions de ${names[child]} sumen Xp. La constància multiplica els punts i acosta els premis.`,`${names[child]}'s missions earn Xp. Consistency multiplies points and brings rewards closer.`)}</p></div><Image src="/task-experience-emoji.png" alt="" width={180} height={180}/></section>
    <div className="rules-diagram" aria-label={t('Misiones, Xp, bonus y premios','Missions, Xp, bonus i premis','Missions, Xp, bonuses and rewards')}>
      <div><Check/><strong>{t('Misiones','Missions','Missions')}</strong></div><b>→</b><div><Wallet/><strong>Xp</strong></div><b>→</b><div><Sparkles/><strong>×2 / ×5</strong></div><b>→</b><div><Gift/><strong>{t('Premios','Premis','Rewards')}</strong></div>
    </div>
    <div className="rules-cards">
      <article className="rules-card"><CalendarDays/><h2>{t('Los bonus van de lunes a domingo','Els bonus van de dilluns a diumenge','Bonuses run Monday to Sunday')}</h2><p>{t('Cada misión cuenta los días y repeticiones que tiene asignados. Las misiones semanales se registran una vez en cualquier día permitido.','Cada missió compta els dies i repeticions assignats. Les missions setmanals es registren una vegada en qualsevol dia permès.','Each mission counts its assigned days and repetitions. Weekly missions are recorded once on any allowed day.')}</p><div className="rules-week">{dayNames[lang].map((d,i)=><span key={i}>{d}</span>)}</div></article>
      <article className="rules-card silver"><Star/><h2>{t('Una misión completa: ×2','Una missió completa: ×2','One complete mission: ×2')}</h2><p>{t('Al terminar todos sus días y repeticiones de la semana, recibes tantos Xp extra como dio esa misión. Una misión de 5 Xp hecha cinco días suma 25 Xp normales y 25 Xp de bonus.','En completar tots els dies i repeticions de la setmana, reps tants Xp extra com ha donat la missió. Una missió de 5 Xp feta cinc dies suma 25 Xp normals i 25 Xp de bonus.','Finish every scheduled day and repetition to earn the same Xp again. A 5 Xp mission done five days earns 25 normal Xp and 25 bonus Xp.')}</p></article>
      <article className="rules-card gold"><Trophy/><h2>{t('Todas las misiones: ×5','Totes les missions: ×5','Every mission: ×5')}</h2><p>{t('Al completar toda la semana, los Xp de esas misiones valen cinco veces más. El ×5 sustituye a los ×2 ya recibidos: solo se añade la diferencia.','En completar tota la setmana, els Xp d’aquestes missions valen cinc vegades més. El ×5 substitueix els ×2 rebuts: només s’afegeix la diferència.','Finish the whole week and mission Xp is worth five times as much. The ×5 replaces earlier ×2 bonuses; only the difference is added.')}</p></article>
      <article className="rules-card"><Moon/><h2>{t('Descansos y correcciones','Descansos i correccions','Rest and corrections')}</h2><p>{t('Los padres pueden programar descansos: esos días dejan de exigirse para el bonus. Si corrigen una misión, el bonus y el saldo se recalculan.','Els pares poden programar descansos: aquests dies deixen de ser necessaris per al bonus. Si corregeixen una missió, el bonus i el saldo es recalculen.','Parents can schedule rest days. Those days stop being required for bonuses. Corrections recalculate bonuses and balances.')}</p></article>
    </div>
    <section className="rules-catalog"><h2>{t(`Misiones de ${names[child]}`,`Missions de ${names[child]}`,`${names[child]}'s missions`)}</h2><p>{t('Los días y los Xp reflejan las reglas configuradas ahora por los padres.','Els dies i els Xp reflecteixen les regles configurades ara pels pares.','Days and Xp reflect the rules currently set by parents.')}</p><div className="rules-task-grid">{tasks.map(task=><article key={task.id}><strong>{words(task.title,lang)}</strong><small>{words(task.description,lang)}</small><b>+{task.xp} Xp {task.cadence==='weekly'?t('por semana','per setmana','per week'):task.limit>1?`× ${task.limit} ${t('veces','vegades','times')}`:''}</b><div className="rules-schedule">{weekDays.map((d,i)=><span key={d} className={task.days.includes(d)?'on':''}>{dayNames[lang][i]}</span>)}</div></article>)}</div></section>
    <section className="rules-reward"><div><span className="eyebrow">{t('PREMIO ESPECIAL','PREMI ESPECIAL','SPECIAL REWARD')}</span><h2><BedDouble/>{reward?words(reward.title,lang):t('Tus premios','Els teus premis','Your rewards')}</h2><p>{t(`Puedes ahorrar Xp durante varias semanas o conseguir una semana perfecta. Al solicitarlo se reservan ${price} Xp; los padres confirman la fecha. Si se cancela, vuelven al saldo.`,`Pots estalviar Xp durant diverses setmanes o aconseguir una setmana perfecta. En demanar-ho es reserven ${price} Xp; els pares confirmen la data. Si es cancel·la, tornen al saldo.`,`Save Xp over several weeks or earn a perfect week. Requesting reserves ${price} Xp; parents confirm the date. Cancellation returns them to your balance.`)}</p><strong>{Math.max(0,balance)} / {price} Xp</strong><button onClick={onRewards}>{t('Ver premios','Veure premis','See rewards')}</button></div><div className="rules-cup"><Image src="/task-experience-emoji.png" alt="" width={220} height={220}/><span>{price} Xp</span></div></section>
    <p className="rules-footnote">{t('Los Xp gastados bajan el saldo, pero no borran la experiencia ni los niveles. Hay pequeñas sorpresas escondidas; las reglas no estropean la búsqueda.','Els Xp gastats baixen el saldo, però no esborren l’experiència ni els nivells. Hi ha petites sorpreses amagades; les regles no espatllen la cerca.','Spent Xp reduce the balance but never erase experience or levels. Small surprises are hidden; the rules leave the hunt intact.')}</p>
  </div>;
}
